version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container2
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
      - dtupay-network
networks:
  dtupay-network:
    # Use a custom driver
    driver: dtupay-driver
 
